// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARewmAQbGpfn1l-BKvACUj7QxvvIvZr6k',
    appId: '1:1078649038581:web:ffcd4cad4c77e25d6747bc',
    messagingSenderId: '1078649038581',
    projectId: 'flutter-chat-app-36603',
    authDomain: 'flutter-chat-app-36603.firebaseapp.com',
    storageBucket: 'flutter-chat-app-36603.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBCcm6-BWabaTdsjpZBnsjPuY7XgDcoq8',
    appId: '1:1078649038581:android:5e5c53f4b24c5bb56747bc',
    messagingSenderId: '1078649038581',
    projectId: 'flutter-chat-app-36603',
    storageBucket: 'flutter-chat-app-36603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mwve7VMnF5tquFy8qh5rMFu1VG_7nhU',
    appId: '1:1078649038581:ios:cac152fa367dee286747bc',
    messagingSenderId: '1078649038581',
    projectId: 'flutter-chat-app-36603',
    storageBucket: 'flutter-chat-app-36603.appspot.com',
    iosBundleId: 'com.example.chatFirebase',
  );
}
